#!/bin/bash 

# WordPress Project Configuration Tool
#
# Automates boilerplate for adding a new LOCAL WordPress project.
# Given a project slug (ensures no spaces, etc.), it adds a URL of type slug.localhost to hosts,
# creates a directory under SIRE_ROOT, and creates a virtual host record in the apache config,
# creates a database schema called slug if it doesn't already exist, and grants the default
# user account full access to it.
#
# Author: 	Patrick Jackson <pjackson@goldenpathsolutions.com>
# Version:	1.1.0
# License: 	GPL2.0
# Created: 	2014-09-10


# add line to make it pretty
printf "\n"

# Title
TITLE="WordPress Project Configuration Tool" # Title of App
# version
VERSION=1.1.0

# defaults
URL_SUFFIX="localhost" 	# appended to the slug to create the URL
IP_ADDRESS="127.0.0.1"	# IP Address associated with the URL in the host file record created
MYSQL_USER="pjackson"	# account to which schema access is granted
SITE_ROOT="/Users/pjackson/Sites"		# by default, the web site directory is added here with 
DIR_OWNER="pjackson:staff"	# owner of the directory created
HOSTS_FILE="/etc/hosts"	# location of hosts file
APACHE_CONFIG="/etc/apache2/users/$SUDO_USER.conf"	# the apache config file to which the virtual host record is added


# define usage
USAGE="\n$TITLE - version $VERSION\n\n\
Usage: projectconfig [ -? | -v | PROJECT_SLUG ]\n\n \
\t-? \t\t: prints full usage message\n \
\t-v \t\t: prints the version\n \
\tPROJECT_SLUG\t: a string of characters that would be allowed as a host name.\n\n \
"
DESCRIPTION="Defaults: \n\tThe following are defined in the application. Listed are the current defaults.  Edit the app to change these.\n\n \
\tURL_SUFFIX = $URL_SUFFIX\n\tAppended to PROJECT_SLUG to create the project URL (PROJECT_SLUG.URL_SUFFIX)\n\n \
\tIP_ADDRESS = $IP_ADDRESS\n\tIP Address associated with the URL in the host file record created\n\n \
\tMYSQL_USER = $MYSQL_USER\n\tThe MySQL account to whom full schema access is granted.  The MySQL schema created is named PROJECT_SLUG\n\n \
\tSITE_ROOT = $SITE_ROOT\n\tThe project directory is created in the SITE_ROOT.  The name of the directory is PROJECT_SLUG\n\n \
\tDIR_OWNER = $DIR_OWNER\n\tThe owner of the site directory created\n\n \
\tAPACHE_CONFIG = $APACHE_CONFIG\n\tThe location of the apache config file to which the virtual host record is added\n\n\
Description:\n \
\t1. Adds a record to the host file: PROJECT_SLUG.URL_SUFFIX=IP_ADDRESS.\n \
\t2. Creates a directory if necessary named PROJECT_SLUG in the SITE_ROOT directory.\n \
\t3. Adds a virtual host record to the apache config file located at APACHE_CONFIG.\n \
\t4. Creates a MySQL schema named PROJECT_SLUG, and grants MYSQL_USER full access to it.\n\n \
"

# validate arguments - must be exactly 1
if [ $# -ne 1 ]; then
	printf "$# Arguments found. Requires 1 argument.\n $USAGE"
	exit 1
fi

# Handle special option cases
case "$1" in
	"-?" )
		printf "$USAGE \n $DESCRIPTION"
		exit 1
		;;
	"-v" )
		printf "$TITLE - $VERSION\n\n"
		exit 1
		;;
esac

# Assume $1 is valid PROJECT_SLUG and continue
PROJECT_SLUG=$1


#####################################################################
# Handle addetion of Host URL to Hosts file.  Points URL at localhost
# Insert before END Virtual Hosts, or append to file

PROJECT_URL=$PROJECT_SLUG.$URL_SUFFIX

matchend='# END Virtual Hosts'

# add our bookends if not there already
if ! grep -q "$matchend" $HOSTS_FILE ; then
	printf "# BEGIN Virtual Hosts\n$matchend" >> $HOSTS_FILE
fi

#  if our host doesn't exist already, insert it 
if ! grep -q "$PROJECT_URL" $HOSTS_FILE ; then
 
	sed -i '.bak' 's/# END Virtual Hosts/'"$IP_ADDRESS $PROJECT_URL"'\'$'\n# END Virtual Hosts/' $HOSTS_FILE

	printf "Added $PROJECT_URL to hosts file\n"
	
else

	printf "$PROJECT_URL already exists in hosts file"

fi



##############################################################
# Handle addition of virtual host record in apache config file

ROOTDIR="$SITE_ROOT/$PROJECT_SLUG"

# Create ROOTDIR if necessary, and set the owner
mkdir -p $ROOTDIR
chown $DIR_OWNER $ROOTDIR

printf "Added $ROOTDIR (owned by $DIR_OWNER )\n"

# Add virtual host record if it doesn't already exist
# assume it exists if the root path is found
if ! grep -q "$ROOTDIR" $APACHE_CONFIG ; then

	printf "\n<VirtualHost *:80>\n \
		ServerName $PROJECT_URL \n\
		DocumentRoot $ROOTDIR \n\
		SetEnv APPLICATION_ENV \"development\" \n\
		<Directory $ROOTDIR> \n\
			DirectoryIndex index.php \n\
			AllowOverride All \n\
			Order allow,deny \n\
			Allow from all \n\
		</Directory> \n\
	</VirtualHost> \n" >> $APACHE_CONFIG 

	printf "Added Virtual Host Record\n"

else

	printf "$ROOTDIR already exists in $APACHE_CONFIG"
	
fi

# Restart apache to make changes take effect
apachectl restart

printf "Restarted Apache\n"

# add line to make it pretty
printf "\n"






